# Site settings
title:          PitcherBox | Blog
description:    "PitcherBox is the ultimate platform connecting influencers and event organizers. Discover, connect, and collaborate with top influencers to amplify your events and campaigns. Sign up today and elevate your brand with meaningful partnerships!"
baseurl:        ""
url:            "https://blog.pitcherbox.com"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         PitcherBox

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/pitcherbox-logo.png"
